# Generated by Django 5.2.6 on 2025-12-01 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_lesson_options_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlastactivity',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentlastactivity',
            name='last_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_lesson', to='courses.lesson', verbose_name='остання лекція'),
        ),
        migrations.AlterField(
            model_name='studentlastactivity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='студент'),
        ),
    ]
