# Generated by Django 5.2 on 2026-05-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentLastActivity',
        ),
    ]
