# Generated by Django 5.2.6 on 2025-12-01 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_lesson_options_and_more'),
        ('users', '0002_studentlastactivity_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlastactivity',
            options={'verbose_name': 'остання активність', 'verbose_name_plural': 'останні активності'},
        ),
        migrations.AddConstraint(
            model_name='studentlastactivity',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_activity'),
        ),
        migrations.AlterModelTable(
            name='studentlastactivity',
            table='student_last_activities',
        ),
    ]
