# Generated by Django 5.2.6 on 2025-12-02 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_module_alter_lesson_order_and_more'),
        ('users', '0003_alter_studentlastactivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(verbose_name='завершено?')),
                ('complete_at', models.DateTimeField(auto_now_add=True, verbose_name='дата завершення лекції')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='лекція')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'прогрес лекції',
                'verbose_name_plural': 'прогрес лекцій',
                'db_table': 'lesson_progress',
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_progress')],
            },
        ),
    ]
