# Generated by Django 5.2.6 on 2025-12-06 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_unique_lesson_order'),
        ('users', '0004_studentlessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentLessonProgress',
            new_name='StudentProgress',
        ),
    ]
