services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    command: gunicorn academy.wsgi:application --bind 0.0.0.0:8000 --access-logfile '-'
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bookworm
    env_file:
      - .env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      start_period: 5s
      retries: 5
      timeout: 5s
    restart: unless-stopped

volumes:
  pg_data:
  static_volume:
  media_volume: