services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - .:/usr/src/app:z
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bookworm
    env_file:
      - .env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      start_period: 5s
      retries: 5
      timeout: 5s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: tailwind/Dockerfile
    volumes:
      - ./static:/usr/src/app/static:z
      - node_modules:/usr/src/app/node_modules:z
    restart: always
    depends_on:
      - web
    stdin_open: true
    tty: true

volumes:
  pg_data:
  node_modules: