FROM python:3.13-slim

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

RUN chmod +x ./entrypoint.dev.sh

ENTRYPOINT ["./entrypoint.dev.sh"]