FROM node:20-slim AS builder
WORKDIR /usr/src/app

COPY tailwind/package*.json .

RUN npm ci

COPY . .

RUN npm run build


FROM python:3.13-slim

WORKDIR /usr/src/app

RUN mkdir -p /usr/src/app/staticfiles \
    /usr/src/app/media \
    /usr/src/app/cache

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

COPY --from=builder /usr/src/app/static/output.css /usr/src/app/static/

RUN useradd -s /bin/sh -u 1000 nonroot

RUN chown -R nonroot:nonroot /usr/src/app

RUN chmod +x ./entrypoint.prod.sh

USER nonroot

ENTRYPOINT ["./entrypoint.prod.sh"]