# Generated by Django 5.2.6 on 2025-12-07 10:08

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='назва курса')),
                ('slug', models.SlugField(max_length=155, verbose_name='слаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення курсу')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_image/', verbose_name='зображення')),
                ('short_description', models.TextField(verbose_name='коротко про курс')),
                ('about', models.TextField(verbose_name='про курс')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курси',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='назва теми')),
                ('slug', models.SlugField(max_length=155, verbose_name='слаг')),
                ('content', mdeditor.fields.MDTextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення теми')),
                ('order', models.PositiveIntegerField(verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'лекція',
                'verbose_name_plural': 'лекції',
                'db_table': 'lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='назва модулю')),
                ('slug', models.SlugField(max_length=155, verbose_name='слаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення модулю')),
                ('note', models.TextField(verbose_name='опис модулю')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'модуль',
                'verbose_name_plural': 'модулі',
                'db_table': 'module',
                'ordering': ['order'],
            },
        ),
    ]
