# Generated by Django 5.2.6 on 2025-11-25 19:24

import django.db.models.deletion
import mdeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Назва теми')),
                ('slug', models.SlugField(max_length=155, verbose_name='Слаг')),
                ('content', mdeditor.fields.MDTextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення теми')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Лекція',
                'verbose_name_plural': 'Лекції',
                'db_table': 'lesson',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Назва курса')),
                ('slug', models.SlugField(max_length=155, verbose_name='Слаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення курсу')),
                ('content', models.TextField(verbose_name='Контент сторінки')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(verbose_name='Завершено?')),
                ('complete_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершення лекції')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='Лекція')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Прогрес лекції',
                'verbose_name_plural': 'Прогрес лекцій',
                'db_table': 'lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Назва модулю')),
                ('slug', models.SlugField(max_length=155, verbose_name='Слаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення модулю')),
                ('note', models.TextField(verbose_name='Опис модулю')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='Порядок')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модулі',
                'db_table': 'module',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.module'),
        ),
    ]
