# Generated by Django 5.2.6 on 2025-11-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(default=2, verbose_name='Про курсе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=2, upload_to='course_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default=2, verbose_name='Коротко про курсе'),
            preserve_default=False,
        ),
    ]
