# Generated by Django 5.2.6 on 2025-11-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_about_course_image_course_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
    ]
