# Generated by Django 5.2.6 on 2025-11-12 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='step',
            name='slug',
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(default=2, verbose_name='Порядок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.course'),
        ),
    ]
