# Generated by Django 5.2.6 on 2025-11-18 07:43

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_step_options_remove_step_slug_step_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='markdown_description',
            field=markdownx.models.MarkdownxField(default=2),
            preserve_default=False,
        ),
    ]
