# Generated by Django 5.2.6 on 2025-12-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'відгук', 'verbose_name_plural': 'відгуки'},
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
