# Generated by Django 5.2.6 on 2025-11-18 07:54

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_step_markdown_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='markdown_description',
        ),
        migrations.AlterField(
            model_name='step',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
