# Generated by Django 5.2.6 on 2025-12-01 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students_alter_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курси'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'лекція', 'verbose_name_plural': 'лекції'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'прогрес лекції', 'verbose_name_plural': 'прогрес лекцій'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'модуль', 'verbose_name_plural': 'модулі'},
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(verbose_name='про курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image/', verbose_name='зображення'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='власник'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(verbose_name='коротко про курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=155, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=155, verbose_name='назва курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення теми'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.module', verbose_name='модуль'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=155, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=155, verbose_name='назва теми'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='complete_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата завершення лекції'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_complete',
            field=models.BooleanField(verbose_name='завершено?'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson', verbose_name='лекція'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення модулю'),
        ),
        migrations.AlterField(
            model_name='module',
            name='note',
            field=models.TextField(verbose_name='опис модулю'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='порядок'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=155, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=155, verbose_name='назва модулю'),
        ),
    ]
