# Generated by Django 5.2.6 on 2025-12-28 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Максимальне допустиме значення - 5'), django.core.validators.MinValueValidator(1, message='Мінімальне допустиме значення - 1')], verbose_name='рейтинг'),
        ),
    ]
