# Generated by Django 5.2.6 on 2025-11-18 19:27

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_step_markdown_description_alter_step_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=martor.models.MartorField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='content',
            field=models.TextField(verbose_name='Контент сторінки'),
        ),
    ]
