# Generated by Django 5.2.6 on 2025-12-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_module_alter_lesson_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_lesson_order'),
        ),
    ]
