# Generated by Django 5.2.6 on 2025-11-18 20:11

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
