# Generated by Django 5.2.6 on 2025-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lesson_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
