# Generated by Django 5.2.6 on 2025-11-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_user_lessonprogress_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='Порядок'),
        ),
    ]
