# Generated by Django 5.2 on 2026-01-17 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='назва')),
                ('price', models.PositiveIntegerField(unique=True, verbose_name='ціна')),
                ('features', models.TextField(verbose_name='переваги')),
                ('duration_days', models.PositiveIntegerField(verbose_name='інтервал плану')),
            ],
            options={
                'verbose_name': 'план',
                'verbose_name_plural': 'плани',
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='дата покупки')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='дата завершення')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan', verbose_name='план')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='студент')),
            ],
            options={
                'verbose_name': 'підписка',
                'verbose_name_plural': 'підписки',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='дата покупки')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='дата завершення')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan', verbose_name='план')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='студент')),
            ],
            options={
                'verbose_name': 'історія підписки',
                'verbose_name_plural': 'історія підписки',
                'db_table': 'subscription_histories',
            },
        ),
    ]
