# Generated by Django 5.2.6 on 2025-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='дата покупки')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='дата покупки')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='назва')),
                ('price', models.PositiveIntegerField(unique=True, verbose_name='ціна')),
                ('features', models.TextField(verbose_name='переваги')),
                ('duration_days', models.PositiveIntegerField(verbose_name='інтервал плану')),
            ],
        ),
    ]
