# Generated by Django 5.2.6 on 2026-01-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_rename_subscriptionplan_plan_subscriptionhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'план', 'verbose_name_plural': 'плани'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'підписка', 'verbose_name_plural': 'підписки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionhistory',
            options={'verbose_name': 'історія підписки', 'verbose_name_plural': 'історія підписки'},
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
        migrations.AlterModelTable(
            name='subscriptionhistory',
            table='subscription_history',
        ),
    ]
