# Generated by Django 5.2.6 on 2026-01-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_plan_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
    ]
