# Generated by Django 5.2.6 on 2026-01-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_plan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscriptions',
        ),
        migrations.AlterModelTable(
            name='subscriptionhistory',
            table='subscription_histories',
        ),
    ]
